version: '3.1'
services:
  product-service:
    image: betulcetinkaya/product-service:${TAG}
    container_name: product-service
    env_file: docker-compose.env
    ports:
      - 8081:8081
    networks:
        - services
networks:
  services:
    external:
      name: services
