version: '3.1'
services:
  product-service:
    image: docker.pkg.github.com/betulcetinkaya/product-service/${BRANCH}:${TAG}
    container_name: product-service
    env_file: docker-compose.env
    ports:
      - 8081:8081
    networks:
        - services
networks:
  services:
    external:
      name: services
